### ISSUE TITLE
Required: Visual Overhaul in Character Creation

### ISSUE THREAD

**Issue by JustinOmariLao** [MiloFisher/AdventuresOfOld#11]
- Different typeface for most, if not all text
- Scrollbar doesn't move in-line with the action (i.e. goes up when player scrolls down)
- Readability is challenged through multiple issues such as text coloring (i.e. bright green on white background), format of text and typeface, transparency of textbox

**Comment by Brwonze** [comment]
Yes sir, will work on this after class today (7PM)
