### ISSUE TITLE
Need Debuff Icons

### ISSUE THREAD

**Issue by MiloFisher** [MiloFisher/AdventuresOfOld#5]
Need the following debuff icons:
<s>-Bleeding</s>
-Burning
-Dazed
-Plagued
<s>-Poisoned</s>
-Enwebbed
-Eaten
<s>-Weakened</s>

**Comment by pbsulliv** [comment]
-Bleed and Poison Icons finished.

**Comment by pbsulliv** [comment]
-Weakened Icon Finished.

**Comment by pbsulliv** [comment]
All debuff Icons finished.
